### ISSUE TITLE
Recursive macro evaluation

### ISSUE THREAD

**Issue by ganoze** [centreon/centreon-engine#1]
We should add the possibility to recursively evaluate all macros in Centreon Engine.

**Comment by ganoze** [comment]
Comment from pierrecdn:

Today it seems that using $USERn$ macros in custom macros doesn't works.
But nevertheless this is usefull when you want to write one command and negate it for example.

generic "mycommand" command : $_SERVICENEGATE$ $USER1$/mycommand.pl -myarg $ARG1$

service1 using mycommand : it works.
service2 using mycimmand :

    macro : NEGATE : /usr/local/nagios/negate -u OK : it works.
    macro : NEGATE : $USER1$/negate -u OK : it doesn't works.

Or there is a best practice ?

pch

**Comment by nicutor** [comment]
Hello, 

Is there any update on this? We are waiting from about 2 years now.

**Comment by ganoze** [comment]
Hi @nicutor 

Unfortunately it is highly likely that we will not release this feature. The first reason is that this feature was developped in the 2.x branch of Centreon Engine. For the time being we will stick with the 1.x branch. So backporting this feature would require an amount of work that we are not willing to process.

The second reason is that this feature would break the setup of many users while providing enhancements to few users. It might be wrong but that is what we've heard so far.

So I will close this ticket. Future will tell us if this feature will be asked again.

**Comment by nicutor** [comment]
Hi @ganoze 

I don't understand why this is not implemented on centreon web panel level. Why this need to be on the engine? Can be so easily to add this as a feature of centreon, and then centreon knows where and what to place on engine configuration..

**Comment by ganoze** [comment]
The current macro resolution system is placed in Centreon Engine because some macro values have a value that change during runtime. We do not plan on placing the macro resolution system in two different places because that would be difficult to maintain.

**Comment by CPbN** [comment]
Another example where this could be useful :
a global `$CENTREONPLUGINSSNMP$` macro containing the following :
`--snmp-autoreduce --snmp-timeout=1 --snmp-retries=7 --authprotocol=SHA --privprotocol=AES --snmp-version=$_HOSTSNMPVERSION$ --snmp-community=$_HOSTSNMPCOMMUNITY$ --snmp-username=$_HOSTSNMPUSER$ --authpassphrase=$_HOSTSNMPPASS$ --privpassphrase=$_HOSTSNMPPASS$`
