### ISSUE TITLE
Notification Interval

### ISSUE THREAD

**Issue by ganoze** [centreon/centreon-engine#10]
As reported by Loic Fontaine:
- On programme un nouveau service avec une notification interval bien définie
- On pousse la configuration sur le poller avec un Reload
- Le premier check se fait et la notification est envoyée après la validation de l'état
- On modifie le service en modification la notification interval
- On pousse la configuration sur le poller avec un Reload
- La nouvelle notification interval n'est pas pris en compte
- On pousse la configuration sur le poller avec un Restart : ça fonctionne

**Comment by ganoze** [comment]
@afouille could you check this one ?

**Comment by SylvestreG** [comment]
normally fixed in 19.10.

Please re-open if not.
