### ISSUE TITLE
Host template choose by typing name

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-engine#102]
Hi,

Could you please add enhancement to host configurations regarding templates.
I would really like if it would be possible to choose/find the correct host template by typing. Currently I have over 100 templates, and due to that I always need know how the template name starts when scrolling through the list.
With Services templates the option is there.

**Comment by lpinsivy** [comment]
It's a Centreon enhancement (https://github.com/centreon/centreon/issues)
