### ISSUE TITLE
Blocage du script d'installation de centreon sous ubuntu 14.10 lors de la configuration de /etc/init.d/centengine

### ISSUE THREAD

**Issue by ganoze** [centreon/centreon-engine#11]
As reported by Thomas Esteve:

Bonjour,

Lors d'une installation fraiche sur un serveur Ubuntu 14.10 (Utopic)
Après installation de centreon-clib -engine et -broker depuis les sources
Lors du lancement du script 'install.h -i' de centreon-2.5.4
A la question :

> What is the Monitoring engine init.d script ?
> 
> > /etc/init.d/centengine

Le script ne trouve pas /etc/init.d/centengine, et pour cause : lors du cmake de centreon-engine la doc stipule -DWITH_STARTUP_DIR=/etc/init.d
Alors que ce n'est pas un script init.d mais un fichier startup.conf qui doit se situer dans /etc/init

Qu'à cela ne tienne : un 'mv /etc/init.d/centengine.conf /etc/init' permet de remettre le script généré à sa place,

MAIS remplacer le init.d par le startup.conf dans l'install ne fonctionne toujours pas :

> What is the Monitoring engine init.d script ?
> 
> > /etc/init/centengine.conf

Le script bloque en boucle sous prétexte que ce fichier n'est pas exécutable
les startup.conf sont lancés via la commande 'service mondaemon start' et ne sont effectivement pas exécutables.

WORKAROUND :

j'ai tenté de tricher en soumettant

> > /usr/bin/service centengine
> > service centengine

sans succès... je l'ai donc berné en mettant

> > /bin/echo

mais je me retrouve avec un sudoers pollué ainsi que probablement certains champs dans la base que je n'ai pas encore cherché.

**Comment by abalam666** [comment]
Hello
Pas d'avancée là dessus... ? Je me retrouve sur ce même problème :-/
Ou as-tu mis le /bin/echo ?

**Comment by ganoze** [comment]
I've issued a pull-request on Centreon repository (centreon/centreon#4067). If accepted, this will solve this issue by allowing any startup command to be set (defaulting to **service centengine** or **service cbd** for Centreon Engine and Centreon Broker respectively).

**Comment by abalam666** [comment]
Ok for me.

**Comment by SylvestreG** [comment]
We've switch for systemd. I don't think this issue is still relevant.
