### ISSUE TITLE
[Enhancement] Add a macro called $POLLERNAME$

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon-engine#113]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**:  18.10
**OS**: RHEL 7

**Additional environment details (AWS, VirtualBox, physical, etc.):**
VM

**Steps to reproduce the issue:**
Is it possible to add a macro called $POLLERNAME$ which returns the hostname of the poller ?

**Comment by lolokai** [comment]
Up ?

**Comment by lolokai** [comment]
Up ?

**Comment by SylvestreG** [comment]
Hi,

Sorry for the long time without answer. Even if you request looks like a small change, adding a $POLLERNAME$ macro needs some change that are not located in engine.

For the moment there is now reference about POLLERNAME in engine configuration files. So if we that feature, we will need to update configuration files generated by centreon-web.

@lpinsivy do you want to plan a feature like that for 20.04 ?

**Comment by lpinsivy** [comment]
Yes we will plan this for 20.04

**Comment by SylvestreG** [comment]
It is merged in 20.04. This will be present in next release.

Cheers,
