### ISSUE TITLE
Allow pipe in plugin output (split at last pipe found)

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-engine#115]
Hi,

Today, a plugin can't put a pipe in its output, as it would lead to a wrongly truncated _short_output_, and corrupted _perfdata_.

For exemple :
`My nice output with | a pipe | perf=1, data=2`
_short_output_ will contain `My nice output with`
_perfdata_ will then point to `a pipe | perf=1, data=2` which of course will be ignored.

However, plugin could legitimately put a pipe in its output.
Let's take the `apps::protocols::http::expectedcontent::plugin` from the [Centron-Plugins](https://github.com/centreon/centreon-plugins/blob/master/apps/protocols/http/mode/expectedcontent.pm).
An `--expected-string` can be given, for example :
`--expected-string=(string1|string2)`
Plugin then outputs :
`OK: '(string1|string2)' is prensent in content. | 'time'=0.058s;;;0; 'size'=2646B;;;0;`

I think it would then be nice to allow plugin output to contain a pipe.
For this, plugin output could be split using the last pipe found (instead of using the first found).
This will work, as performance data can't contain a pipe.

I had a look into the code, and I think the culprit is here :
https://github.com/centreon/centreon-engine/blob/18.10.0/src/utils.cc#L470
Perhaps we could replace `strtok` by `strrchr` ?

Thank you very much for your help & support !

Edit : issue still present in 19.04.3 (engine 19.04.1).

**Comment by CPbN** [comment]
Hi,
Any news regarding this please ?
Now, with Centreon Plugins, there are many opportunities to use `|` character in plugin options, leading to the above explained issue.
I just faced it again, wrong perfdata received by the broker and sent to InfluxDB Stream connector script...

Should be rather easy to split at last pipe ?

Thank you very much !

**Comment by bouda1** [comment]
Sorry we forgot this issue.
I think you are right and it would be pretty easy to implement it.
Just we are on the centreon release 19.04. And for now the code is frozen.
But it should be fixed soon.

**Comment by CPbN** [comment]
Thank you very much for your answer @bouda1 :+1:
Arf, did not know the code was frozen :)
Will be for next release then !
Thank you again.

**Comment by bouda1** [comment]
This is fixed for the next centreon-engine release.
I cannot tell you when it will be available, many things are changing in this new version and we have much things to check before the release. But this is fixed in the refacto-engine branch.
Cheers.

**Comment by CPbN** [comment]
Really good news @bouda1, thank you very much :+1: 
I'll test and report once released :)
Thank you again !

**Comment by CPbN** [comment]
I confirm this is fixed in _19.10.0-beta.2_.
Thank you 👍
