### ISSUE TITLE
Consistency for home directory

### ISSUE THREAD

**Issue by centreon** [centreon/centreon-engine#15]
Charles Judith Write here : https://forge.centreon.com/issues/4419

I think it's good to take this point in account in order to start the new generation of RPM (new version of Engine) with this fix.

---------------------------------------
Hi,

Here is home directories for centreon users:

  centreon: x :101:102::/var/spool/centreon:/bin/bash
  centreon-broker: x :102:103::/var/spool/centreon-broker:/bin/bash
  centreon-engine: x :104:105::/var/lib/centreon-engine:/bin/bash

I think it will be better to have consistency for home directory for these users.

What do you think about that ?

Thanks,

**Comment by ganoze** [comment]
Fixed in next major version of RPMs.
