### ISSUE TITLE
Problème avec les Downtimes Glissant

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon-engine#22]
Pour reproduire le bug :
 - Programmer un Downtime Time non fixe sur un service et/ou plusieurs services (Downtime assez long : 1 an par exemple)
 - Une fois le downtime appliqué, supprimer le downtime dans "Monitoring ==> DOwntimes"
 - Redémarrer le moteur de supervision : Le downtime n'a pas été supprimé et est de nouveau appliqué

**Comment by ganoze** [comment]
Merci beaucoup pour ton retour.

Malheureusement je n'arrive pas à reproduire le problème que tu décris avec les dernières versions de la suite Centreon. Peu importe la configuration du downtime (fixe, non-fixe, long, court, démarré, non-démarré) ils ne réapparaissent jamais après un redémarrage de l'Engine qu'ils aient été annulés ou supprimés.

Peux-tu m'envoyer un fichier de debug Engine généré pendant la manipulation (démarrage initial, création du downtime, suppression du downtime, redémarrage et apparition du downtime) ?

**Comment by ganoze** [comment]
Timeout
