### ISSUE TITLE
last_state_change and last_hard_state_change have the same value

### ISSUE THREAD

**Issue by querwin** [centreon/centreon-engine#23]
In database "last_state_change" and "last_hard_state_change" have the same value.

They should not be the same.

**Comment by afouille** [comment]
Hi,

This has been tested with centreon-engine 1.4.14-3 and last_state_change/last_hard_state_change work as expected. What exactly are the step to reproduce this problem?

Cordially,

**Comment by ganoze** [comment]
Timeout.

**Comment by garnier-quentin** [comment]
I have that problem. An example:
```
service is hard/warning:
       last_check: 1498208479
       last_hard_state: 1
       last_hard_state_change: 1498208479
       last_state_change: 1498208479

service is hard/critical:
       last_check: 1498208532
       last_hard_state: 2
       last_hard_state_change: 1498208532
       last_state_change: 1498208532
```

It should be like that no ?
```
      last_check: 1498208532
      last_hard_state: 2
      last_hard_state_change: 1498208479
      last_state_change: 1498208532
```

**Comment by ganoze** [comment]
@garnier-quentin IMHO it seems consistent that _last_hard_state_change_ is updated if _last_hard_state_ changes. Do you agree ?

**Comment by garnier-quentin** [comment]
For me the hard state doesn't change. The 'state' change (warning -> critical) but not the hard state (it stays HARD). no ?

**Comment by ganoze** [comment]
In Centreon Engine terminology the **hard state** does change. The **state type** does not. However *last_hard_state_change* refers to _hard state_ transition.

**Comment by garnier-quentin** [comment]
So what is the diff between the two values ? Because you have last_state_change when it comes from warning -> critical.

**Comment by ganoze** [comment]
*last_state_change* is updated as soon as the current state is updated (SOFT or HARD) whereas *last_hard_state_change* is updated only for HARD states.

**Comment by garnier-quentin** [comment]
We don't have an attribute with the value since last hard state appear ?

**Comment by garnier-quentin** [comment]
Unfortunately, i cannot. I need one attribute for the request.
