### ISSUE TITLE
Enhancement - Add a variable to show host relationships on notifications

### ISSUE THREAD

**Issue by ddu17** [centreon/centreon-engine#25]
Hello,

I set all relationships on my hosts and I would like to show childs or parents hosts in notifications sent for a host. This possibility will be usefull for my techies.

Best regards.

**Comment by ganoze** [comment]
We will add the HOSTPARENTS and HOSTCHILDREN macros. @afouille could you implement these new macros ?

**Comment by afouille** [comment]
@ganoze certainly. See 32b2941280c115e1e793c04411ce1e6432fbdf73
