### ISSUE TITLE
Perl connector problem

### ISSUE THREAD

**Issue by kadrika** [centreon/centreon-engine#26]
Hi,

I run into a problem where cent engine.log shows lot of errors like this:
Error: Service check command execution failed: Connector 'Perl Connector' failed to restart

Do you have any ideas, what can cause this?

How can I restart the connector myself?

**Comment by ganoze** [comment]
Do you have Centreon Connector Perl installed ?
Is its path properly configured for Centreon Engine ?
Is Centreon Connector Perl binary executable ?

**Comment by kadrika** [comment]
Yes, we have Perl connector installed.
Command is: /usr/lib64/centreon-connector/centreon_connector_perl --code "use lib '/usr/lib/nagios/plugins/'\;"

But I just checked and the error is not showing up anymore, so it must have been temporary issue.

**Comment by ganoze** [comment]
Perfect ! Therefore I'm closing this ticket.

**Comment by kadrika** [comment]
And we have the problem again. And with that error in logs, at the same time the graphs of new services are also not drawn.

**Comment by kadrika** [comment]
And also it seems that the graphs problem is completely different problem we have, because again new services do not draw graphs, but the logs do not show the perl error. And our admin just told me that the graph problem is related to user rights.

**Comment by ganoze** [comment]
Could you provide the Centreon Engine log and debug files generated when the connector error is happening ? If these files contain sensitive data you can email them to me at mkermagoret@centreon.com.

**Comment by kadrika** [comment]
Hi,
I opened a ticket about it to Centreon support, so I hope they will check it and reply to it via the ticket. Or maybe you can take a look at it?

**Comment by ganoze** [comment]
I've had no feedback from Centreon support. Is this issue still open ?

**Comment by kadrika** [comment]
No, you can close the case. We got it resolved under the ticket. But thanks for the help!

**Comment by eleektro** [comment]
kadrika, what was the problem?

**Comment by kadrika** [comment]
Hi,

If I remember it correctly, then we had nagios and centengine process running at the same time. After the nagios process was stopped and centengine restarted the problem was solved.

**Comment by eleektro** [comment]
Hey, kadrika, thanks! That do the trick!
