### ISSUE TITLE
[BUG] - 2 notifications sent for recovery - passive service

### ISSUE THREAD

**Issue by pkriko** [centreon/centreon-engine#268]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Centreon Web version**: 
19.10.1
**Centreon Engine version**: 
19.10.0
**Centreon Broker version**: 
19.10.0
**OS**: 
CentOS 7.7
**Additional environment details (AWS, VirtualBox, physical, etc.):**

**Steps to reproduce the issue:**
1. Create passive service attach to any host
2. submit result on this passive service with CRITICAL status
3. submit result on this passive service with OK status

**Describe the results you received:**
2 notifications have been sent :
![image](https://user-images.githubusercontent.com/32265250/67217485-17191d80-f425-11e9-9760-730f676cb8ad.png)

In the centengine-log :
```
[1571660129] [12623] SERVICE NOTIFICATION: root_localhost;Centreon;test-passif;OK;service-notify-by-email;(No output returned from plugin)
[1571660129] [12623] SERVICE NOTIFICATION: root_localhost;Centreon;test-passif;RECOVERY (OK);service-notify-by-email;(No output returned from plugin)
```

**Describe the results you expected:**
Only the RECOVERY notfication must be send.

**Additional information you think important (e.g. issue happens only occasionally):**

**Comment by bouda1** [comment]
It will be fixed in centreon engine 19.10.8
