### ISSUE TITLE
Unreachable hosts, unexpected UP notifications

### ISSUE THREAD

**Issue by UrBnW** [centreon/centreon-engine#280]
Hi,

I'm facing the following issue :

![sc](https://user-images.githubusercontent.com/40244829/67760681-09295500-fa42-11e9-829c-54c97c305bff.png)

_b0g1_ depends on _tec_.
_tec_ dies so we receive a DOWN notification, perfect.
_b0g1_ then becomes unavailable, and as contacts are not configured to receive UNREACHABLE alerts, no such notification is sent, perfect.
_tec_ comes back online, we then receive a UP notification.
But we also receive a UP notification for _b0g1_, which is IMO not expected.

A bug perhaps ?

Many thanks 👍

**Comment by lpinsivy** [comment]
Hi @CPbN , looking "Nagios" official documentation, it didn't look a bug event if the concept is wierd.

UNREACHABLE is a status as RECOVERY or DOWN and you can filter status that you want to receive for notification.

But yes for the concept, if you don't want to receive UNREACHABLE notification, it could be interested to do not receive the associated RECOVERY notification.

**Comment by CPbN** [comment]
Hi @lpinsivy, thank you for your answer and interest into this 👍

You're right, I just configured a test contact not to receive DOWN alert.
So he did not receive DOWN alert, but received the RECOVERY one.

This hosts behavior is rather strange.
With services, if contact does not receive the UNKNOWN / WARNING / CRITICAL notification, he will not receive the OK one...

> But yes for the concept, if you don't want to receive UNREACHABLE notification, it could be interested to do not receive the associated RECOVERY notification.

Exactly 👍
Think about a core router down, with hundreds of UNREACHABLE hosts behind 😑 ...

Thank you again !

**Comment by CPbN** [comment]
Just for info, as per [the doc](https://documentation.centreon.com/docs/centreon-engine/en/latest/user/configuration/basics/notifications.html#service-and-host-filters) :
_Notifications about host or service recoveries are only sent out if a notification was sent out for the original problem. It doesn’t make sense to get a recovery notification for something you never knew was a problem._

So this PR does seem to be a bug :)

**Comment by UrBnW** [comment]
@lpinsivy could you re-flag this as a bug then ? Many thx 👍

**Comment by UrBnW** [comment]
Last 19.10 engine fixes this bug, certainly thanks to #415 (and #407 in 20.10).
I then close this, thank you.
