### ISSUE TITLE
Notifications: no notification on hard-state change

### ISSUE THREAD

**Issue by CPbN** [centreon/centreon-engine#294]
Hi,

I face the following issue :

![Screen Shot 2019-11-17 at 19 51 24](https://user-images.githubusercontent.com/40244829/69012238-e8368e80-0973-11ea-8796-abda4049eab7.png)

I would have expected to receive a CRITICAL notification, but it is not triggered.
I initially faced this on various services, and just reproduced it as shown above to open this ticket.

I then think you should easily reproduce it.

Thank you 👍

Edit : issue still present in centreon-engine 19.10.6.

**Comment by CPbN** [comment]
Another example :

![Screen Shot 2019-11-18 at 20 28 25](https://user-images.githubusercontent.com/40244829/69083421-5b0e3b00-0a42-11ea-8d83-b7ee6ba8f27d.png)

OK notification did not fired-up either (certainly because of the missing CRITICAL one ?) ...

Rather uncomfortable as a bug 😕

**Comment by bouda1** [comment]
Hi @CPbN 
You should have a fix for this very soon.

**Comment by CPbN** [comment]
Hi @bouda1,
Really good news, glad to see you managed to find / reproduce the issue 👍
Many thanks !

**Comment by bouda1** [comment]
Should be fixed in Engine 19.10.8

**Comment by CPbN** [comment]
Good news David, I'll test and let you know as soon as released.
Thank you :+1:

**Comment by CPbN** [comment]
Just tested, now works as expected, perfect, many thanks !
