### ISSUE TITLE
Warning message: 'has no default contacts or contactgroups defined' : option to display

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-engine#30]
Hi,

Could you use add an option to display warning message when we test configuration ?

**Comment by julienmathis** [comment]
@garnier-quentin You want this messages or not ?

I think this kind or message is useless. When a user clic "disable notification", he should not have to give a contact or a contact group. It's completely crazy and useless ! 
My feeling is : "simplify the configuration at the maximum". 

Small company are using notification but big industry are using only visual errors on a screen (with dedicated people in a noc) to ack errors. Notifications are not usefull.

**Comment by garnier-quentin** [comment]
For me, i don't want it. No need for that.
