### ISSUE TITLE
Question - Compatibility with nagios plugins

### ISSUE THREAD

**Issue by nicutor** [centreon/centreon-engine#31]
Hi,

This is just a question. I've read about centreon-engine that was started  using the nagios 3x. 
Can you tell me if the centreon-egine is compatible with all nagios plugins and work in the same way?

Thanks

**Comment by ganoze** [comment]
The current major development branch (1.x) is expected to work perfectly fine with all plugins respecting the [Nagios Plugin Developement Guidelines](https://nagios-plugins.org/doc/guidelines.html).

It is also expected to work with most common modules made for Nagios 3 like MKlivestatus, mod_gearman, DNX, ...

I hope that this will answer your question. If not, feel free to reply on this thread.
