### ISSUE TITLE
timezone and macro $TIMEZONE$

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-engine#34]
Hi,

There is timezone management in centreon-engein 1.5.x. It will be great to have a macro $TIMEZONE$ to use it in commands.

Best regards,

**Comment by afouille** [comment]
Hi,

I added the macros HOSTTIMEZONE and SERVICETIMEZONE.

Regards,

**Comment by afouille** [comment]
Added CONTACTTIMEZONE by popular demand.

**Comment by lolokai** [comment]
Your macro $HOSTTIMEZONE$ doesn't works with Centreon Engine 1.5.1

**Comment by ganoze** [comment]
Timezone macros were not integrated in the 1.5 branch. I'm currently merging the development branch within the 1.6 branch. So these macros will be available with the next Centreon Engine release.

Thank you for reopening this ticket.
