### ISSUE TITLE
[1.5.0] Duplicate services

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon-engine#38]
Parfois lors de Reload, les services sont dupliqués et parfois même les services supprimés ne sont pas supprimés.

Tout rentre dans l'ordre si on fait un restart

**Comment by ganoze** [comment]
Avez-vous des exemples de marche à suivre à me donner ? Cela a-t-il lieu suite à des évènements particuliers ?

**Comment by lolokai** [comment]
Cela a commencé après la migration vers Centreon Engine 1.5 sinon rien de spécial nous avons travaillé sur la plateforme comme sur la version 1.4.x.
Il n'y a rien de particulier dans le fichier de debug si ce n'est qu'il ajoute le service sans supprimer l'ancien

**Comment by ganoze** [comment]
Pouvez-vous me faire parvenir les éléments suivants couvrant la période où le bug se produit.

  - fichiers de configuration
  - fichier de log
  - fichier de debug
  - fichier de retention (retention.dat)

Si besoin vous pouvez me communiquer ces éléments par mail (mkermagoret@centreon.com).

**Comment by lolokai** [comment]
Mon collaborateur t'envoi les fichiers.

**Comment by afouille** [comment]
Bonjour,

Je prends le relais sur ce problème.

Pouvez-vous me donner le nom d'un service impacté par ce bug? Ainsi que le fichier de logs brokers central-module et central-master configurés pour tout logger durant la période de production de ce bug?

Si besoin, mon adresse mail est la suivante (afouille@centreon.com).

**Comment by afouille** [comment]
Bonjour,

Ce problème est fixé dans le commit 234fbf47abecfd4b8fffdb7eb629b3899496d85b. La prochaine version de Centreon-Broker (2.12.0) intégrera ce correctif.

Cordialement,

**Comment by lolokai** [comment]
Merci :)
