### ISSUE TITLE
Poller sudently not run

### ISSUE THREAD

**Issue by prohand** [centreon/centreon-engine#384]
Hello,

Since this morning when everything was working my poller no longer transmits information to the central.

Can you help me please ?

Log of pooler :

`[root@s-centreonpoller centreon-gorgone]# tail -f gorgoned.log
2020-05-04 09:19:39 - INFO - [core] Module 'engine' is loaded
2020-05-04 09:19:39 - INFO - [core] Module 'dbcleaner' is loading
2020-05-04 09:19:39 - INFO - [core] Module 'dbcleaner' is loaded
2020-05-04 09:19:39 - INFO - [core] Gorgoned started
2020-05-04 09:19:39 - INFO - [core] PID 792
2020-05-04 09:19:39 - INFO - [dbcleaner] Create module 'dbcleaner' process
2020-05-04 09:19:39 - INFO - [engine] Create module 'engine' process
2020-05-04 09:19:39 - INFO - [action] Create module 'action' process
2020-05-04 09:19:39 - INFO - [core] Server accepting clients
2020-05-04 09:21:17 - INFO - [core] Connection from proxy-1-3
2020-05-04 09:25:14 - INFO - [core] Connection from proxy-1-3
service centcore status^C
[root@s-centreonpoller centreon-gorgone]# service centcore status
Redirecting to /bin/systemctl status centcore.service
Unit centcore.service could not be found.
[root@s-centreonpoller centreon-gorgone]# service cbd status
Redirecting to /bin/systemctl status cbd.service
Unit cbd.service could not be found.
[root@s-centreonpoller centreon-gorgone]# service gorgoned status
Redirecting to /bin/systemctl status gorgoned.service
● gorgoned.service - Centreon Gorgone
Loaded: loaded (/etc/systemd/system/gorgoned.service; enabled; vendor preset: disabled)
Active: active (running) since lun. 2020-05-04 09:19:37 CEST; 11min ago
Main PID: 792 (perl)
CGroup: /system.slice/gorgoned.service
├─ 792 /usr/bin/perl /usr/bin/gorgoned --config=/etc/centreon-gorg...
├─1311 gorgone-dbcleaner
├─1312 gorgone-engine
└─1319 gorgone-action

mai 04 09:19:37 s-centreonpoller systemd[1]: Started Centreon Gorgone.
[root@s-centreonpoller centreon-gorgone]#
`
Log of central :

`[root@s-centreon xxxx]# service gorgoned status
Redirecting to /bin/systemctl status gorgoned.service
● gorgoned.service - Centreon Gorgone
Loaded: loaded (/etc/systemd/system/gorgoned.service; enabled; vendor preset: disabled)
Active: active (running) since lun. 2020-05-04 09:24:58 CEST; 6min ago
Main PID: 877 (perl)
CGroup: /system.slice/gorgoned.service
├─ 877 /usr/bin/perl /usr/bin/gorgoned --config=/etc/centreon-gorg...
├─1187 gorgone-nodes
├─1188 gorgone-dbcleaner
├─1189 gorgone-autodiscovery
├─1196 gorgone-cron
├─1197 gorgone-engine
├─1204 gorgone-statistics
├─1212 gorgone-action
├─1220 gorgone-httpserver
├─1236 gorgone-legacycmd
├─2031 gorgone-proxy
├─2038 gorgone-proxy
├─2045 gorgone-proxy
├─2052 gorgone-proxy
└─2059 gorgone-proxy

mai 04 09:24:58 s-centreon systemd[1]: Started Centreon Gorgone.
[root@s-centreon xxxx]# nano /etc/profile.local^C
[root@s-centreon xxxx]# tail -f /var/log/centreon-gorgone/gorgoned.log
2020-05-04 09:35:00 - INFO - [cron] Launching job 'engine_stats'
2020-05-04 09:35:00 - INFO - [statistics] Collecting Engine statistics from target '1'
2020-05-04 09:35:19 - INFO - [core] Setcoreid changed 1
2020-05-04 09:35:19 - INFO - [proxy] Recreate session for 3
2020-05-04 09:35:20 - INFO - [proxy] PongReset received from '3'
2020-05-04 09:35:25 - INFO - [zmqclient] Client connected successfully to 'tcp://192.9.250.116:5556'
2020-05-04 09:35:25 - INFO - [proxy] Received setlogs for '3'
2020-05-04 09:35:45 - INFO - [proxy] Send pings
2020-05-04 09:35:45 - INFO - [proxy] Pong received from '3'
2020-05-04 09:36:45 - INFO - [proxy] Received setlogs for '3'
`
Last update of poller : 4 mai 2020 06:38:10

Reboot poller and central are no effect.
I update the centreon-gorgone with the last update and restart centegine but no effect.

It's related to this : https://github.com/centreon/centreon-gorgone/issues/27

Thank you

**Comment by bouda1** [comment]
Hi,

I see many things on gorgone is your message.
Several questions:
* does centengine always run, or is it stopped?
* Does 'systemctl -p warning ' reports about centengine crash?
* Do you have errors reported in cbd logs or in centengine logs?

Regards.

**Comment by prohand** [comment]
Yes centegine is run one poller and central.
systemctl -p warning does not report centengine crash 

I have this error in : central-broker-master.log

`[1588541768] error:   BBDO: peer tcp://x.x.x.x:58938 is sending corrupted data: invalid CRC`

Thank you

**Comment by bouda1** [comment]
Ok. We are working on a patch to fix this. I hope it will be available soon.

Could you send the input configuration block of your central-broker.json configuration file and also the output configuration block of your central-module.json.
Thanks.

**Comment by prohand** [comment]
central-broker.json : 

`{
    "centreonBroker": {
        "broker_id": 1,
        "broker_name": "central-broker-master",
        "poller_id": 1,
        "poller_name": "Central",
        "module_directory": "/usr/share/centreon/lib/centreon-broker",
        "log_timestamp": true,
        "log_thread_id": false,
        "event_queue_max_size": 100000,
        "command_file": "/var/lib/centreon-broker/command.sock",
        "cache_directory": "/var/lib/centreon-broker",
        "input": [
            {
                "name": "central-broker-master-input",
                "port": "5669",
                "buffering_timeout": "0",
                "retry_interval": "60",
                "protocol": "bbdo",
                "tls": "auto",
                "negotiation": "yes",
                "one_peer_retention_mode": "no",
                "compression": "auto",
                "type": "ipv4"
            }
        ],
        "logger": [
            {
                "name": "/var/log/centreon-broker/central-broker-master.log",
                "config": "yes",
                "debug": "no",
                "error": "yes",
                "info": "no",
                "level": "low",
                "type": "file"
            }
        ],
        "output": [
            {
                "name": "central-broker-master-sql",
                "db_type": "mysql",
                "db_host": "localhost",
                "buffering_timeout": "0",
                "retry_interval": "60",
                "db_port": "3306",
                "db_user": "centreon",
                "db_password": "cenbddcen3lc1a*",
                "db_name": "centreon_storage",
                "check_replication": "no",
                "type": "sql"
            },
            {
                "name": "centreon-broker-master-rrd",
                "port": "5670",
                "buffering_timeout": "0",
                "retry_interval": "60",
                "host": "localhost",
                "protocol": "bbdo",
                "tls": "no",
                "negotiation": "yes",
                "one_peer_retention_mode": "no",
                "compression": "no",
                "type": "ipv4"
            },
            {
                "name": "central-broker-master-perfdata",
                "interval": "60",
                "length": "15552000",
                "buffering_timeout": "0",
                "retry_interval": "60",
                "db_type": "mysql",
                "db_host": "localhost",
                "db_port": "3306",
                "db_user": "centreon",
                "db_password": "cenbddcen3lc1a*",
                "db_name": "centreon_storage",
                "check_replication": "no",
                "store_in_data_bin": "yes",
                "insert_in_index_data": "1",
                "type": "storage"
            }
        ],
        "stats": [
            {
                "type": "stats",
                "name": "central-broker-master-stats",
                "json_fifo": "/var/lib/centreon-broker/central-broker-master-stats.json"
            }
        ],
        "grpc": {
            "port": 51001
        }
    }
`

central-module.json : 

`{
    "centreonBroker": {
        "broker_id": 3,
        "broker_name": "central-module-master",
        "poller_id": 1,
        "poller_name": "Central",
        "module_directory": "/usr/share/centreon/lib/centreon-broker",
        "log_timestamp": false,
        "log_thread_id": false,
        "event_queue_max_size": 100000,
        "command_file": "",
        "cache_directory": "/var/lib/centreon-engine",
        "logger": [
            {
                "name": "/var/log/centreon-broker/central-module-master.log",
                "config": "yes",
                "debug": "no",
                "error": "yes",
                "info": "no",
                "level": "low",
                "type": "file"
            }
        ],
        "output": [
            {
                "name": "central-module-master-output",
                "port": "5669",
                "host": "localhost",
                "retry_interval": "60",
                "buffering_timeout": "0",
                "protocol": "bbdo",
                "tls": "no",
                "negotiation": "yes",
                "one_peer_retention_mode": "no",
                "compression": "no",
                "type": "ipv4"
            }
        ],
        "stats": [
            {
                "type": "stats",
                "name": "central-module-master-stats",
                "json_fifo": "/var/lib/centreon-engine/central-module-master-stats.json"
            }
        ],
        "grpc": {
            "port": 51003
        }
    }
`

**Comment by prohand** [comment]
Hello,

Problem solved after :

```
yum --enablerepo="centreon-unstable*" update centreon-gorgone
yum --enablerepo="centreon-unstable*" update centreon-engine
```
Thank you

**Comment by prohand** [comment]
Hello,

The problem happened again today

Same message in log.

Thank you

**Comment by prohand** [comment]
I rebooted without success.
I then relaunch the order on the central and pollute it
yum --enablerepo = "centreon-unstable *" update centreon-gorgone
I rebooted again and the problem is solved but until when?

Thank you

**Comment by bouda1** [comment]
Maybe you can update centreon-broker to the 20.04.1 version. It contains a fix about your issue.
Another one is in preparation, but not ready...

**Comment by prohand** [comment]
Ok Thank you. The problem is solved after use last centreon-gorgone and centreon-engine in unstable repo
