### ISSUE TITLE
[1.5.0] Parent relations

### ISSUE THREAD

**Issue by lolokai** [centreon/centreon-engine#39]
Centreon Engine ne semble plus détecter les relations Parents/Enfants : Lorsque le parent tombe, l'enfant est toujours vu comme DOWN et non en UNREACHABLE

**Comment by bouda1** [comment]
Bonjour,

En fait, le comportement est bien celui attendu sur les checks actifs. Par contre, pour un check passif, on a le comportement que vous décrivez.
