### ISSUE TITLE
[2.7.1] Contact with Enable Notifications set to NO still receive email 

### ISSUE THREAD

**Issue by Thiefoumongars** [centreon/centreon-engine#40]
Good day,

Since the upgrade of my Centreon platform to the version 2.7.1, all my contacts which was having notification disabled start receiving all notifications.
Is anybody has the same issue ?

I have test the most simple configuration, mean without any inheritance (no group contact, no template contact, no host template.......)
Contact with notification disable linked to a host ..... and the user receive the notification in case of UP or down...

Thanks for your help.

**Comment by ganoze** [comment]
The issue came from Centreon Web. The bug was fixed in the 2.7.2 release. Therefore I'm closing this ticket.
