### ISSUE TITLE
Pb latency

### ISSUE THREAD

**Issue by jben94** [centreon/centreon-engine#41]
Bonjour,

A plusieurs reprises j'ai constaté un problème de latence, ce problème arrive de façon aléatoire.

La latence atteint une valeur aberrante (exemple: **1456719256.562702**), je suis désolé mais comme je ne peux pas reproduire le problème, je n'ai pas de log à fournir.
Mais comme vous pouvez le voir dans l'exemple ci-dessus, le début me fait pensé à un timestamp. 
Peut-être un problème de calcul ou de concaténation de deux variables.

**Comment by Sims24** [comment]
Bonjour, 

Est-ce que l'option "process-service-perfdata" est bien à 0 dans votre centengine.cfg ?

**Comment by jben94** [comment]
Bonjour,

L'option est bien désactivé.
A la suite de la mise à jour de ma plate-forme (Broker et WEB), le problème n'est pas réapparu donc je vais fermer le ticket.

Désolé pour le dérangement.
