### ISSUE TITLE
Disable service check of dependent hosts

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon-engine#42]
Hi, 

Would you think that implementing a feature allowing user to define if services of dependent host should be check (or not) could be a good idea ? 

e.g : 

-> my host A depends upon my host B.
-> If my host B is down then my host A is not checked anymore
-> With the proposed feature, setting the option to yes would disable all the service checks of my host B.

Thanks,

**Comment by ganoze** [comment]
IMHO we should always keep polling services. This behavior is far more understandable. Doing otherwise requires new developments and is error prone.

However, @lpinsivy the decision is up to you. What do you think about this proposal ?

**Comment by lpinsivy** [comment]
Dependencies have to be used for that.
