### ISSUE TITLE
Compatibility nagios-centreon

### ISSUE THREAD

**Issue by andrea46r** [centreon/centreon-engine#465]
Hi, sorry but i have i question:
before starting i wanted to know if old versions of nagios (3.4.x) are compatible with centreon 20.10 or not.
Thanks for help

**Comment by Sims24** [comment]
Hi, 

No, Engine is not compatible at all with Nagios 3.4.x. Nevertheless you can convert you Nagios configuration to a Centreon one with nagiosToCentreon tool.

**Comment by omercier** [comment]
Hi @andrea46r 
As @Sims24 said, you can use [this tool](https://github.com/centreon/nagiosToCentreon) to convert your Nagios conf.
