### ISSUE TITLE
$ADMINEMAIL$ not populated on notification command

### ISSUE THREAD

**Issue by angeleseros** [centreon/centreon-engine#484]
We recently upgraded our centreon to v20.10 and I have a notification command as follows:

define command {
    command_name                   host-notify-by-email-html-v2 
    command_line                   /bin/sh -c '/usr/lib/centreon/custom/bash/notification_via_sendmail_html Date="$DATE$" Time="$TIME$" NotificationType="$NOTIFICATIONTYPE$" Host="$HOSTNAME$" Alias="$HOSTALIAS$" Address="$HOSTADDRESS$" ID="$HOSTPROBLEMID$" PREVID="$LASTHOSTPROBLEMID$" State="$HOSTSTATE$" AdditionalInfo="$HOSTOUTPUT$<br>[$HOSTACKAUTHOR$]: $HOSTACKCOMMENT$" To="$CONTACTEMAIL$" From=" $ADMINEMAIL$" Subject="** Host $HOSTSTATE$ alert for $HOSTNAME$ **" LOGFILE="/var/log/centreon-engine/host_notification_via_sendmail.log"' 
}

the /usr/lib/centreon/custom/bash/notification_via_sendmail_html  is a custom script that formats the values to HTML.

the $ADMINEMAIL$ is no longer being passed down

is the $ADMINEMAIL$ been changed to other macro? Thanks

**Comment by omercier** [comment]
Hi @angeleseros,
Please can you tell me from which version of Centreon you upgraded to 20.10?
I will then try to investigate about it.
Thanks!

**Comment by angeleseros** [comment]
From version 18.10

**Comment by angeleseros** [comment]
Additional Info:

Alert Macros $HOSTACKAUTHOR$, $HOSTACKCOMMENT$, $SERVICEACKAUTHOR$, and $SERVICEACKCOMMENT$ seems to be empty as well when doing acknowledgements.

**Comment by angeleseros** [comment]
I have tested on a newly installed centreon 20.10.7 with the following notification command:

/usr/bin/printf "%b" "***** centreon Notification *****\n\nNotification Type: $NOTIFICATIONTYPE$\n\nService: $SERVICEDESC$\nHost: $HOSTALIAS$\nAddress: $HOSTADDRESS$\nState: $SERVICESTATE$\n\nDate/Time: $DATE$ Additional Info : $SERVICEOUTPUT$\nACK Author: $SERVICEACKAUTHOR$\nACK Comment: $SERVICEACKCOMMENT$\nAdmin Email Address: $ADMINPAGER$ <$ADMINEMAIL$>" | @MAILER@ -s "** $NOTIFICATIONTYPE$ alert - $HOSTALIAS$/$SERVICEDESC$ is $SERVICESTATE$ **" $CONTACTEMAIL$


and did an acknowledgement of a dummy service on critical and received the following:

***** centreon Notification *****

Notification Type: ACKNOWLEDGEMENT

Service: generic-dummy-service-custom
Host: generic-dummy-host
Address: 1.1.1.1
State: CRITICAL

Date/Time: 2021-05-17 Additional Info : CRITICAL: Dummy Service
ACK Author:
ACK Comment:
Admin Email Address:  <>

**Comment by omercier** [comment]
Hi @angeleseros, 
Thanks for your feedback.
The bug is identified and reproduced.
We will fix it soon.
Internal reference: MON-11761

**Comment by joschi99** [comment]
Hi @omercier,
we have still the same issue with empty marco $ADMINEMAIL$ on version 22.04.

Any information regarding this?

**Comment by omercier** [comment]
Hi Jochen,
Sorry, this regression has been left aside for a while.
We have re-priorized the ticket in our backlog to fix it soon.
PS: for further issues, please use https://github.com/centreon/centreon-collect/

**Comment by joschi99** [comment]
Thanks for the info. Do you have a idea when the problem should be fixed?

PS: The support through Github is for open source as I know. But if I understand correctly we should open cases for commercial support now also in Github?

Please let me know.

Regards,
Jochen

***@***.***<https://www.i-vertix.com/>
www.i-vertix.com<https://www.i-vertix.com/>
***@***.***<https://www.linkedin.com/company/i-vertix/>
***@***.***<https://www.youtube.com/channel/UCa38ZZWVFpCX5XhY8v0UFnQ>
***@***.***<https://www.facebook.com/iVertix/>
Jochen Platzgummer
CEO
Mobile: +39 335 277070<tel:0039335277070>
Phone: +39 0471 1430171<tel:003904711430171>
Mail: ***@***.******@***.***>
Teams: ***@***.******@***.***>
***@***.***<https://www.i-vertix.com/>
Le informazioni contenute in questa comunicazione e relativi allegati possono essere riservate e sono, comunque, destinate esclusivamente ai destinatari sopraindicati.
La diffusione, distribuzione e/o copiatura del documento trasmesso da parte di qualsiasi soggetto diverso dal destinatario è vietata ai sensi del Regolamento UE 2016/679 (GDPR).
Se avete ricevuto questo messaggio per errore, vi preghiamo di distruggerlo informandoci immediatamente scrivendoci una mail all'indirizzo ***@***.******@***.***>. Per visualizzare
l'informativa sul trattamento dei dati personali effettuato da PGUM S.r.l. consultare la nostra Privacy Policy<https://i-vertix.com/condizioni-generali/>.
