### ISSUE TITLE
[200624.177750] centengine[3146283]: segfault at 40 ip 0000000000793b9c sp 00007ffe8d1b55c0 error 4 in centengine[400000+7a9000]

### ISSUE THREAD

**Issue by PsichoD** [centreon/centreon-engine#487]
centengine segfaults shortly after starting. It always exists at the same point: segfault at 40 ip 0000000000793b9c sp 00007ffe8d1b55c0 error 4 in centengine[400000+7a9000]

***Versions***
centreon-21.04.0-3.el8.noarch
centreon-auto-discovery-server-21.04.0-1.el8.noarch
centreon-base-config-centreon-engine-21.04.0-3.el8.noarch
centreon-broker-21.04.0-7.el8.x86_64
centreon-broker-cbd-21.04.0-7.el8.x86_64
centreon-broker-cbmod-21.04.0-7.el8.x86_64
centreon-broker-core-21.04.0-7.el8.x86_64
centreon-broker-storage-21.04.0-7.el8.x86_64
centreon-clib-21.04.0-1.el8.x86_64
centreon-common-21.04.0-3.el8.noarch
centreon-connector-21.04.0-1.el8.x86_64
centreon-connector-perl-21.04.0-1.el8.x86_64
centreon-connector-ssh-21.04.0-1.el8.x86_64
centreon-database-21.04.0-3.el8.noarch
centreon-engine-21.04.0-10.el8.x86_64
centreon-engine-daemon-21.04.0-10.el8.x86_64
centreon-engine-extcommands-21.04.0-10.el8.x86_64
centreon-gorgone-21.04.0-4.el8.noarch
centreon-gorgone-centreon-config-21.04.0-4.el8.noarch
centreon-license-manager-21.04.0-1.el8.noarch
centreon-license-manager-common-21.04.0-1.el8.noarch
centreon-perl-libs-21.04.0-3.el8.noarch
centreon-plugin-Applications-Databases-Mysql-20210421-093317.el8.noarch
centreon-plugin-Applications-Monitoring-Centreon-Central-20210421-093317.el8.noarch
centreon-plugin-Applications-Monitoring-Centreon-Database-20210421-093317.el8.noarch
centreon-plugin-Applications-Monitoring-Centreon-Map4-Jmx-20210421-093317.el8.noarch
centreon-plugin-Applications-Monitoring-Centreon-Poller-20210421-093317.el8.noarch
centreon-plugin-Applications-Protocol-Dns-20210421-093317.el8.noarch
centreon-plugin-Applications-Protocol-Ftp-20210421-093317.el8.noarch
centreon-plugin-Applications-Protocol-Http-20210421-093317.el8.noarch
centreon-plugin-Applications-Protocol-Ldap-20210421-093317.el8.noarch
centreon-plugin-Hardware-Printers-Generic-Snmp-20210421-093317.el8.noarch
centreon-plugin-Hardware-Ups-Standard-Rfc1628-Snmp-20210421-093317.el8.noarch
centreon-plugin-Network-Cisco-Standard-Snmp-20210421-093317.el8.noarch
centreon-plugin-Operatingsystems-Linux-Snmp-20210421-093317.el8.noarch
centreon-plugin-Operatingsystems-Windows-Snmp-20210421-093317.el8.noarch
centreon-poller-centreon-engine-21.04.0-3.el8.noarch
centreon-pp-manager-21.04.0-1.el8.noarch
centreon-release-21.04-4.el8.noarch
centreon-trap-21.04.0-3.el8.noarch
centreon-web-21.04.0-3.el8.noarch
centreon-widget-engine-status-21.04.0-1.el8.noarch
centreon-widget-global-health-21.04.0-1.el8.noarch
centreon-widget-graph-monitoring-21.04.0-1.el8.noarch
centreon-widget-grid-map-21.04.0-1.el8.noarch
centreon-widget-hostgroup-monitoring-21.04.0-1.el8.noarch
centreon-widget-host-monitoring-21.04.0-2.el8.noarch
centreon-widget-httploader-21.04.0-3.el8.noarch
centreon-widget-live-top10-cpu-usage-21.04.0-1.el8.noarch
centreon-widget-live-top10-memory-usage-21.04.0-1.el8.noarch
centreon-widget-servicegroup-monitoring-21.04.0-1.el8.noarch
centreon-widget-service-monitoring-21.04.0-1.el8.noarch
centreon-widget-tactical-overview-21.04.0-1.el8.noarch

***Operating System***

CentOS Linux release 8.3.2011

***How the the component has been installed and versions***

From packages

Version: --

oVirt based VM.

### Description

-- Describe the encountered issue --

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. I upgraded Centreon from version 20.10 to version 21.04 by using the YUM repo.
2. I restarted centengine from the Web UI, after performing version update via the UI prompts. There was no issues during the update.
3. 

### Describe the received result
centengine segfaults shortly after being restarted with no clear indication of the cause.

### Describe the expected result
centengine should remain running.
### Logs

Apr 25 23:31:04 vm-s5.securinux.net centengine[3147261]: [1619382664] [3147261] Processing object config file '/etc/centreon-engine/escalations.cfg'
Apr 25 23:31:04 vm-s5.securinux.net centengine[3147261]: [1619382664] [3147261] Processing object config file '/etc/centreon-engine/dependencies.cfg'
Apr 25 23:31:04 vm-s5.securinux.net centengine[3147261]: [1619382664] [3147261] Processing object config file '/etc/centreon-engine/connectors.cfg'
Apr 25 23:31:04 vm-s5.securinux.net centengine[3147261]: [1619382664] [3147261] Processing object config file '/etc/centreon-engine/meta_commands.cfg'
Apr 25 23:31:04 vm-s5.securinux.net centengine[3147261]: [1619382664] [3147261] Processing object config file '/etc/centreon-engine/meta_timeperiod.cfg'
Apr 25 23:31:04 vm-s5.securinux.net centengine[3147261]: [1619382664] [3147261] Processing object config file '/etc/centreon-engine/meta_host.cfg'
Apr 25 23:31:04 vm-s5.securinux.net centengine[3147261]: [1619382664] [3147261] Processing object config file '/etc/centreon-engine/meta_services.cfg'
Apr 25 23:31:04 vm-s5.securinux.net centengine[3147261]: [1619382664] [3147261] Reading resource file '/etc/centreon-engine/resource.cfg'
Apr 25 23:32:09 vm-s5.securinux.net systemd[1]: centengine.service: Main process exited, code=dumped, status=11/SEGV
Apr 25 23:32:09 vm-s5.securinux.net systemd[1]: centengine.service: Failed with result 'core-dump'.

**Comment by PsichoD** [comment]
Here is a core debug:

coredumpctl dump 
           PID: 3147648 (centengine)
           UID: 1165600106 (centreon-engine)
           GID: 1165600106 (centreon-engine)
        Signal: 11 (SEGV)
     Timestamp: Sun 2021-04-25 23:38:53 IDT (11min ago)
  Command Line: /usr/sbin/centengine /etc/centreon-engine/centengine.cfg
    Executable: /usr/sbin/centengine
 Control Group: /system.slice/centengine.service
          Unit: centengine.service
         Slice: system.slice
       Boot ID: 759cbf80a0ce43a0a54137c56a3750d3
    Machine ID: 1ead957c74df4f1f8694f8ed4c93c401
      Hostname: vm-s5.securinux.net
       Storage: /var/lib/systemd/coredump/core.centengine.1165600106.759cbf80a0ce43a0a54137c56a3750d3.3147648.1619383133000000.lz4
       Message: Process 3147648 (centengine) of user 1165600106 dumped core.
                
                Stack trace of thread 3147648:
                #0  0x0000000000793b9c _ZL19get_host_group_nameRN3com8centreon6engine4hostEP13nagios_macros (centengine)
                #1  0x00000000007939c4 grab_standard_host_macro_r (centengine)
                #2  0x00000000007a1b9b _ZL17handle_host_macroP13nagios_macrosiRKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_RS6_Pi (centengine)
                #3  0x0000000000787a6f _ZN3com8centreon6engine8commands3raw26_build_macrosx_environmentER13nagios_macrosRNS2_11environmentE (centengine)
                #4  0x00000000007881a3 _ZN3com8centreon6engine8commands3raw25_build_environment_macrosER13nagios_macrosRNS2_11environmentE (centengine)
                #5  0x000000000078855a _ZN3com8centreon6engine8commands3raw3runERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEER13nagios_macrosj (centengine)
                #6  0x00000000006bfcc5 _ZN3com8centreon6engine4host15run_async_checkEidbbPbPl (centengine)
                #7  0x00000000006c0198 _ZN3com8centreon6engine4host19run_scheduled_checkEid (centengine)
                #8  0x0000000000792449 _ZN3com8centreon6engine11timed_event22_exec_event_host_checkEv (centengine)
                #9  0x00000000007927f7 _ZN3com8centreon6engine11timed_event18handle_timed_eventEv (centengine)
                #10 0x000000000078cc38 _ZN3com8centreon6engine6events4loop12_dispatchingEv (centengine)
                #11 0x000000000078d7c8 _ZN3com8centreon6engine6events4loop3runEv (centengine)
                #12 0x000000000066138f main (centengine)
                #13 0x00007fc97a2a17b3 __libc_start_main (libc.so.6)
                #14 0x0000000000667fce _start (centengine)
                
                Stack trace of thread 3147659:
                #0  0x00007fc97af7e2fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007fc96a1305bc _ZN4asio6detail9scheduler3runERSt10error_code (cbmod.so)
                #2  0x00007fc96a12975e _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN3com8centreon6broker4poolC4EmEUlvE_EEEEE6_M_runEv (cbmod.so)
                #3  0x00007fc97ac9dba3 execute_native_thread_routine (libstdc++.so.6)
                #4  0x00007fc97af7814a start_thread (libpthread.so.0)
                #5  0x00007fc97a37af23 __clone (libc.so.6)
                
                Stack trace of thread 3147649:
                #0  0x00007fc97af7e2fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x0000000000894d52 gpr_cv_wait (centengine)
                #2  0x00000000007e330b _ZN9grpc_core8Executor10ThreadMainEPv (centengine)
                #3  0x00000000008968b3 _ZZN9grpc_core12_GLOBAL__N_120ThreadInternalsPosixC4EPKcPFvPvES4_PbRKNS_6Thread7OptionsEENUlS4_E_4_FUNES4_ (centengine)
                #4  0x00007fc97af7814a start_thread (libpthread.so.0)
                #5  0x00007fc97a37af23 __clone (libc.so.6)
                
                Stack trace of thread 3147650:
                #0  0x00007fc97af7e2fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x0000000000894d52 gpr_cv_wait (centengine)
                #2  0x00000000007e330b _ZN9grpc_core8Executor10ThreadMainEPv (centengine)
                #3  0x00000000008968b3 _ZZN9grpc_core12_GLOBAL__N_120ThreadInternalsPosixC4EPKcPFvPvES4_PbRKNS_6Thread7OptionsEENUlS4_E_4_FUNES4_ (centengine)
                #4  0x00007fc97af7814a start_thread (libpthread.so.0)
                #5  0x00007fc97a37af23 __clone (libc.so.6)
                
                Stack trace of thread 3147653:
                #0  0x00007fc97af7e2fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007fc97ac978f0 _ZNSt18condition_variable4waitERSt11unique_lockISt5mutexE (libstdc++.so.6)
                #2  0x000000000078574b _ZN3com8centreon6engine8commands9connector13_restart_loopEv (centengine)
                #3  0x00007fc97ac9dba3 execute_native_thread_routine (libstdc++.so.6)
                #4  0x00007fc97af7814a start_thread (libpthread.so.0)
                #5  0x00007fc97a37af23 __clone (libc.so.6)
                
                Stack trace of thread 3147654:
                #0  0x00007fc97af7e2fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007fc97ac978f0 _ZNSt18condition_variable4waitERSt11unique_lockISt5mutexE (libstdc++.so.6)
                #2  0x000000000078574b _ZN3com8centreon6engine8commands9connector13_restart_loopEv (centengine)
                #3  0x00007fc97ac9dba3 execute_native_thread_routine (libstdc++.so.6)
                #4  0x00007fc97af7814a start_thread (libpthread.so.0)
                #5  0x00007fc97a37af23 __clone (libc.so.6)
                
                Stack trace of thread 3147652:
                #0  0x00007fc97a37b257 epoll_wait (libc.so.6)
                #1  0x000000000087d520 _ZL12pollset_workP12grpc_pollsetPP19grpc_pollset_workerl (centengine)
                #2  0x00000000007fcc33 _ZL7cq_nextP21grpc_completion_queue12gpr_timespecPv (centengine)
                #3  0x00000000007d0e48 _ZN9grpc_impl15CompletionQueue17AsyncNextInternalEPPvPb12gpr_timespec (centengine)
                #4  0x00000000007c29d0 _ZN9grpc_impl6Server24SyncRequestThreadManager11PollForWorkEPPvPb (centengine)
                #5  0x00000000007cf45c _ZN4grpc13ThreadManager12MainWorkLoopEv (centengine)
                #6  0x00000000007cf65c _ZN4grpc13ThreadManager12WorkerThread3RunEv (centengine)
                #7  0x00000000008968b3 _ZZN9grpc_core12_GLOBAL__N_120ThreadInternalsPosixC4EPKcPFvPvES4_PbRKNS_6Thread7OptionsEENUlS4_E_4_FUNES4_ (centengine)
                #8  0x00007fc97af7814a start_thread (libpthread.so.0)
                #9  0x00007fc97a37af23 __clone (libc.so.6)
                
                Stack trace of thread 3147651:
                #0  0x00007fc97af7e6e8 pthread_cond_timedwait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x0000000000894da7 gpr_cv_wait (centengine)
                #2  0x00000000007efa4f _ZL12timer_threadPv (centengine)
                #3  0x00000000008968b3 _ZZN9grpc_core12_GLOBAL__N_120ThreadInternalsPosixC4EPKcPFvPvES4_PbRKNS_6Thread7OptionsEENUlS4_E_4_FUNES4_ (centengine)
                #4  0x00007fc97af7814a start_thread (libpthread.so.0)
                #5  0x00007fc97a37af23 __clone (libc.so.6)
                
                Stack trace of thread 3147657:
                #0  0x00007fc97af7e2fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007fc96a1305bc _ZN4asio6detail9scheduler3runERSt10error_code (cbmod.so)
                #2  0x00007fc96a12975e _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN3com8centreon6broker4poolC4EmEUlvE_EEEEE6_M_runEv (cbmod.so)
                #3  0x00007fc97ac9dba3 execute_native_thread_routine (libstdc++.so.6)
                #4  0x00007fc97af7814a start_thread (libpthread.so.0)
                #5  0x00007fc97a37af23 __clone (libc.so.6)
                
                Stack trace of thread 3147656:
                #0  0x00007fc97af7e2fc pthread_cond_wait@@GLIBC_2.3.2 (libpthread.so.0)
                #1  0x00007fc96a1305bc _ZN4asio6detail9scheduler3runERSt10error_code (cbmod.so)
                #2  0x00007fc96a12975e _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN3com8centreon6broker4poolC4EmEUlvE_EEEEE6_M_runEv (cbmod.so)
                #3  0x00007fc97ac9dba3 execute_native_thread_routine (libstdc++.so.6)
                #4  0x00007fc97af7814a start_thread (libpthread.so.0)
                #5  0x00007fc97a37af23 __clone (libc.so.6)
                
                Stack trace of thread 3147665:
                #0  0x00007fc97a346fc8 __nanosleep (libc.so.6)
                #1  0x00007fc97a372d88 usleep (libc.so.6)
                #2  0x00007fc95edfa189 _ZN3com8centreon6broker5stats6worker4_runEv (15-stats.so)
                #3  0x00007fc97ac9dba3 execute_native_thread_routine (libstdc++.so.6)
                #4  0x00007fc97af7814a start_thread (libpthread.so.0)
                #5  0x00007fc97a37af23 __clone (libc.so.6)
                
                Stack trace of thread 3147666:
                #0  0x00007fc97a346fc8 __nanosleep (libc.so.6)
                #1  0x00007fc97a372d88 usleep (libc.so.6)
                #2  0x00007fc96a154e36 _ZN3com8centreon6broker10processing8failover4_runEv (cbmod.so)
                #3  0x00007fc97ac9dba3 execute_native_thread_routine (libstdc++.so.6)
                #4  0x00007fc97af7814a start_thread (libpthread.so.0)
                #5  0x00007fc97a37af23 __clone (libc.so.6)
                
                Stack trace of thread 3147655:
                #0  0x00007fc97a36fca1 __poll (libc.so.6)
                #1  0x00007fc96adf5253 command_file_worker_thread (externalcmd.so)
                #2  0x00007fc97af7814a start_thread (libpthread.so.0)
                #3  0x00007fc97a37af23 __clone (libc.so.6)
                
                Stack trace of thread 3147669:
                #0  0x00007fc97a36fca1 __poll (libc.so.6)
                #1  0x00007fc97b3a7e91 _ZN3com8centreon15process_manager4_runEv (libcentreon_clib.so)
                #2  0x00007fc97ac9dba3 execute_native_thread_routine (libstdc++.so.6)
                #3  0x00007fc97af7814a start_thread (libpthread.so.0)
                #4  0x00007fc97a37af23 __clone (libc.so.6)
                
                Stack trace of thread 3147658:
                #0  0x00007fc97a37b257 epoll_wait (libc.so.6)
                #1  0x00007fc96a12ebf2 _ZN4asio6detail13epoll_reactor3runElRNS0_8op_queueINS0_19scheduler_operationEEE (cbmod.so)
                #2  0x00007fc96a130499 _ZN4asio6detail9scheduler3runERSt10error_code (cbmod.so)
                #3  0x00007fc96a12975e _ZNSt6thread11_State_implINS_8_InvokerISt5tupleIJZN3com8centreon6broker4poolC4EmEUlvE_EEEEE6_M_runEv (cbmod.so)
                #4  0x00007fc97ac9dba3 execute_native_thread_routine (libstdc++.so.6)
                #5  0x00007fc97af7814a start_thread (libpthread.so.0)
                #6  0x00007fc97a37af23 __clone (libc.so.6)
Refusing to dump core to tty (use shell redirection or specify --output).

**Comment by Sims24** [comment]
Hi, 

Thanks for tracking this, could you send your config files by mail to dboucher@centreon.com / rgres@centreon.com / omercier@centreon.com / sbomm@centreon.com. 

If you could also provide the core dump it would help a lot.

**Comment by PsichoD** [comment]
Hi Simon,

I sent you the core and the logs as requested. Thank you for looking into this!

**Comment by PsichoD** [comment]
A quick update:
To work the issue around I associated all services to at least one service group and all hosts to at least one host group.
centengine no longer crashes.

**Comment by bouda1** [comment]
This bug should be fixed. You just have to update.
Please, reopen the ticket if you still have the issue.
