### ISSUE TITLE
[customvariables] Macro value is coming back

### ISSUE THREAD

**Issue by garnier-quentin** [centreon/centreon-engine#49]
centengine 1.5.1

I have a custom macro with no value. i set the value with 'XXX' for example (with external command).
I remove the macro (with external command) and the macro is well removed. But i use external command 'ENABLE_PASSIVE_SVC_CHECKS' and 'DISABLE_PASSIVE_SVC_CHECKS', the macro value is coming back Oo

**Comment by afouille** [comment]
Hi,

Fixed in the latest branch of Engine/Broker.

Regards,
