### ISSUE TITLE
Centengine crash: "general protection" fault in /var/log/messages

### ISSUE THREAD

**Issue by btassite** [centreon/centreon-engine#51]
CES 3.3 iso, updated to Centreon 2.7.5, right after reloading poller config, line in /var/log/messages:

Jul 22 11:21:38 centreon kernel: centengine[24204] general protection ip:316913382f sp:7f24560320e8 error:0 in libc-2.12.so[3169000000+18a000]

From the shell:
# service centengine status; service centcore status; service cbd status
/etc/init.d/centengine: line 176: kill: (17971) - No such process
centengine status: /usr/sbin/centengine dead with existing [FAILED]: /var/run/centengine.pid
centcore (pid  14044) is running...
cbd (pid  14091) is running...
cbd (pid  14124) is running...

Using the web interface reload option doesn't restart it, "# service centengine start" does, no further problems apparent yet.

**Comment by btassite** [comment]
Update: got a segfault too now on a poller config reload, see bug #52

**Comment by ganoze** [comment]
Does this issue still happen with latest Centreon Engine versions ?

**Comment by btassite** [comment]
Hasn't happened in Centreon 2.7.7 (engine 1.5.1 IIRC) yet, but I stopped testing escalations/exceptions and I have a feeling it's related to that.

**Comment by ganoze** [comment]
Unfortunately without a reproduction of the bug with the latest available version, there is nothing I can do.

Feel free to reopen if you successfully reproduce with latest versions.
