### ISSUE TITLE
Missing conan dependencies when building 21.04.1

### ISSUE THREAD

**Issue by alk-adong** [centreon/centreon-engine#513]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***

For the RPM based systems

-- Copy/Paste the result of the following command --
```
$ rpm -qa | grep centreon
```

- 21.04.1

***Operating System***

Ubuntu 20.04 LTS

***How the the component has been installed and versions***

From source

Version: 21.04.1 aka 6fde671f578e8be94ba0baac37c2099175e3858f

***Additional environment details (AWS, VirtualBox, physical, etc.):***

### Description

When trying to build centreon-engine from source, I get the following error when trying to run conan:

```
centreon-engine/build$ conan install --build missing ..
Configuration:
[settings]
arch=x86_64
arch_build=x86_64
build_type=Release
compiler=gcc
compiler.libcxx=libstdc++
compiler.version=9
os=Linux
os_build=Linux
[options]
[build_requires]
[env]

gtest/1.8.1@bincrafters/stable: Not found in local cache, looking in remotes...
gtest/1.8.1@bincrafters/stable: Trying with 'conan-center'...
Downloading conanmanifest.txt completed [0.35k]
Downloading conanfile.py completed [4.04k]
Downloading conan_export.tgz completed [0.74k]
Decompressing conan_export.tgz completed [0.00k]
gtest/1.8.1@bincrafters/stable: Downloaded recipe revision 0
json11/e2e3a11@centreon/stable: Not found in local cache, looking in remotes...
json11/e2e3a11@centreon/stable: Trying with 'conan-center'...
json11/e2e3a11@centreon/stable: Trying with 'centreon'...
ERROR: Unable to find 'json11/e2e3a11@centreon/stable' in remotes
```

### Steps to Reproduce

- Clone centreon-engine
- Checkout the 21.04.1 tag
- Create build directory, cd, run `conan install --build missing ..`

Note: Same issue applies to the centreon-connectors repository

Thanks,

**Comment by bouda1** [comment]
Hi,

Yes we know that, this because of the bintray repo that has closed.

We have switched to the conan-center repo.

So to be able to compile centreon-engine, you have to try to compile the next 21.04.2 branch or the 21.04.x branch.

**Comment by alk-adong** [comment]
Alright thanks.

Do you happen to know if patch releases get published on download.centreon.com, and will there be a github release for 21.04.2?
