### ISSUE TITLE
CMake Error protobuf building 20.04.11

### ISSUE THREAD

**Issue by landregen** [centreon/centreon-engine#518]
# BUG REPORT INFORMATION

### Prerequisites

> The opened issue, must be code related. GitHub is not meant for support. Feel free to check the CONTRIBUTING section for more details.

***Versions***

Centreon-Engine 20.04.11

***Operating System***

Raspbian

***How the the component has been installed and versions***

From sources

Version: 20.04.11

***Additional environment details (AWS, VirtualBox, physical, etc.):***

### Description

When trying to build centreon-engine from source, I get the following error when trying to run Cmake:

`CMake Error at CMakeLists.txt:47 (find_package):
  By not providing "Findprotobuf.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "protobuf",
  but CMake did not find one.

  Could not find a package configuration file provided by "protobuf" with any
  of the following names:

    protobufConfig.cmake
    protobuf-config.cmake

  Add the installation prefix of "protobuf" to CMAKE_PREFIX_PATH or set
  "protobuf_DIR" to a directory containing one of the above files.  If
  "protobuf" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!`

### Steps to Reproduce

Please describe precisely the steps to reproduce the encountered issue.

1. git clone -b 20.04.11 https://github.com/centreon/centreon-engine
2. mkdir build
3. cd build
4. CXXFLAGS=-latomic conan install --build=grpc --build=fmt --build=missing ..
5. cmake  \
    -DWITH_CENTREON_CLIB_INCLUDE_DIR=/usr/include  \
    -DWITH_CENTREON_CLIB_LIBRARY_DIR=/usr/lib  \
    -DWITH_PREFIX=/usr  \
    -DWITH_PREFIX_BIN=/usr/sbin  \
    -DWITH_PREFIX_CONF=/etc/centreon-engine  \
    -DWITH_USER=centreon-engine  \
    -DWITH_GROUP=centreon-engine  \
    -DWITH_LOGROTATE_SCRIPT=1 \
    -DWITH_VAR_DIR=/var/log/centreon-engine  \
    -DWITH_RW_DIR=/var/lib/centreon-engine/rw  \
    -DWITH_STARTUP_SCRIPT=systemd  \
    -DWITH_STARTUP_DIR=/lib/systemd/system  \
    -DWITH_PKGCONFIG_SCRIPT=1 \
    -DWITH_PKGCONFIG_DIR=/usr/lib/pkgconfig  \
    -DWITH_TESTING=0  ..

Thanks,

**Comment by omercier** [comment]
Hi, 
There was an issue some months ago when we switched to Conan Center.
I advice you to try compiling all the poller components in one shot in 21.10 by cloning the repo https://github.com/centreon/centreon-collect/

`git clone https://github.com/centreon/centreon-collect/ -b release-21.10.0`
or, when there will be higher versions
`git clone https://github.com/centreon/centreon-collect/ -b 21.10.x`

then 
`cd centreon-collect
./cmake.sh -r
cd build
make
make install`

This will avoid you having to clone all the repos and build them in the right order.
And by the way, the 20.04 is now in "end of life".
