### ISSUE TITLE
Centengine crash: segfault

### ISSUE THREAD

**Issue by btassite** [centreon/centreon-engine#52]
CES 3.3 iso, updated to Centreon 2.7.5

Jul 22 12:27:40 centreon kernel: centengine[1391]: segfault at 5791b470 ip 000000316913382f sp 00007fca775f80e8 error 4 in libc-2.12.so[3169000000+18a000]

# service centengine status; service centcore status; service cbd status
/etc/init.d/centengine: line 176: kill: (24702) - No such process
centengine status: /usr/sbin/centengine dead with existing [FAILED]: /var/run/centengine.pid
centcore (pid  14044) is running...
cbd (pid  14091) is running...
cbd (pid  14124) is running...

"# service centengine start" works to restart it, also see bug #51

**Comment by ganoze** [comment]
Seems like a duplicate of #51.
