### ISSUE TITLE
No notifications are sent for some host services, notifications ARE sent for others

### ISSUE THREAD

**Issue by sandwedge** [centreon/centreon-engine#59]
The behavior is easy to describe, but I'm not sure why it is happening.  I only receive notifications on a few hosts, other hosts will go CRITICAL/HARD without sending a notification.  Looking at their configurations, they are configured almost identically and I can find no indication why notifications wouldn't be sent.  Where can I start with debugging?

CentOS 6.x latest updates.  Centreon installed from RPMs via the official RPM repos:

```
centreon-2.7.6-4.el6.noarch
centreon-base-config-centreon-engine-2.7.6-4.el6.noarch
centreon-broker-2.11.5-2.el6.x86_64
centreon-broker-cbd-2.11.5-2.el6.x86_64
centreon-broker-cbmod-2.11.5-2.el6.x86_64
centreon-broker-core-2.11.5-2.el6.x86_64
centreon-broker-storage-2.11.5-2.el6.x86_64
centreon-clib-1.4.2-1.el6.x86_64
centreon-common-2.7.6-4.el6.noarch
centreon-connector-1.1.2-1.el6.x86_64
centreon-connector-perl-1.1.2-1.el6.x86_64
centreon-connector-ssh-1.1.2-1.el6.x86_64
centreon-engine-1.5.1-3.el6.x86_64
centreon-engine-daemon-1.5.1-3.el6.x86_64
centreon-engine-extcommands-1.5.1-3.el6.x86_64
centreon-perl-libs-2.7.6-4.el6.noarch
centreon-plugin-meta-2.7.6-4.el6.noarch
centreon-plugins-2.7.6-4.el6.noarch
centreon-trap-2.7.6-4.el6.noarch
centreon-web-2.7.6-4.el6.noarch
```

This defined host notifications happen:

```
define host {
    host_name                      working-host.mydomain.com
    alias                          working-host
    address                        working-host.mydomain.com
    contact_groups                 groupA,groupB
    notification_period            24x7
    notification_interval          240
    notification_options           d,u,r
    register                       1
    timezone                       :Europe/Paris
    use                            MyHostTemplate
    _HOST_ID                       34
}


define service {
    host_name                      working-host.mydomain.com
    service_description            Load
    contact_groups                 groupA,groupB
    notification_period            24x7
    notification_interval          240
    register                       1
    use                            check-snmp-linux-load-average
    _SERVICE_ID                    24
}
```

This defined host notifications do not happen:

```
define host {
    host_name                      broken-host.mydomain.com
    alias                          broken-host.mydomain.com
    address                        broken.host.ip.addy
    contact_groups                 groupA,groupB
    notification_period            24x7
    notification_interval          240
    notification_options           d,u,r
    register                       1
    timezone                       :Europe/Paris
    use                            MyHostTemplate
    _HOST_ID                       36
}


define service {
    host_name                      broken-host.mydomain.com
    service_description            http
    contact_groups                 groupA,groupB
    check_command                  check_http!80!/!5!10
    check_period                   24x7
    notification_period            24x7
    notification_interval          240
    register                       1
    use                            generic-service
    _SERVICE_ID                    257
}
```

Here are the service definition templates being used:

```
define service {
    service_description            generic-service
    name                           generic-service
    check_period                   24x7
    notification_period            24x7
    max_check_attempts             3
    check_interval                 5
    retry_interval                 1
    notification_interval          720
    notification_options           w,c,r
    register                       0
    is_volatile                    0
    active_checks_enabled          1
    passive_checks_enabled         0
    notifications_enabled          1
}


define service {
    service_description            Load
    name                           check-snmp-linux-load-average
    check_command                  check_centreon_load_average!4,3,2!6,5,4
    register                       0
    use                            generic-service
}
```

I see in the centreon interface the service goes CRITICAL on both hosts after the 3 rechecks.  Viewing the logs, I see HARD and then NOTIF.  On the broken host, I just see the HARD status with no NOTIF to follow.

It sounds similar to #53 reported by @btassite

**Comment by BornToBeRoot** [comment]
Could this be the same issue: https://github.com/centreon/centreon/issues/5028

I don't know if this was/is a problem with centron or centreon-engine.

For me notification only work for hosts (up/down) but not for services which are assigned to this host (ok/crit/warn). If i add contacts to the service or service template the notification works.

**Comment by btassite** [comment]
BornToBeRoot: judging from your "describe the results you received" it might be the same issue (as well as this issue itself), note though that my #53 seems purely the result of check scheduling:

If the service goes down before the host, notification for the service is sent, then once the host itself goes into down status notification is sent for that too.

If the host goes down before the service goes critical however, no notification is sent for the service, only for the host, regardless of what contacts/contactgroups are defined in templates, in the service itself, for the host etc. This seems a logic bug to me.

Sandwedge: if you could look at the timing for your "broken" host/service combo vs. the "working" one maybe you could confirm that this is a check scheduling issue.

**Comment by BornToBeRoot** [comment]
@btassite I think you misunderstand me. The host is never going down.

I don't get notifications from the services which are assigned to a host.

For example:
The host is up and all services are OK...
When now a service (for example: cpu) reachs critical (95 %), i don't get notified via Mail (there is also no "NOTIF" event in the logs).


The contact groups are assigned to the host and not to the servcices... My workaround was, to link the contact groups direclty to each service. If now a service reachs warn/crit, i get notifications.

According to my understanding (from the documentaiton, bug reports), the contacts which are defined in host, should be used for service notfications as long as there are not overwritten in the service itself.
 
It looks like the inheritance is interrupted between Host and Service, because it has worked in the past versions.

**Comment by btassite** [comment]
Then you ran into something else that has nothing to do with this one and/or #53. As you can see from the host/service definitions above, all 4 have contact groups assigned to them. Similar for my issue, I have contacts/contact groups defined for individual services and it makes no difference, at least #53 is purely timing dependent, this one may turn out to be too (and therefore the same as #53).

**Comment by sandwedge** [comment]
I've revisited this issue again and no matter what I do, I can't seem to get service checks to alert.  Host checks - host down / host up, those email out so I know I have contacts, contact groups, etc.. configured correctly. 

This is a small install with 27 hosts and maybe 250 services.   One of my larger installs is what I'm using for comparison to see if I can find where I'm missing something - larger install is 450 hosts and 5800 services and everything alerts / NOTIF as expected.  I'm not seeing NOTIF called in the logs for the host/service.

**Comment by sandwedge** [comment]
I just moved the install to the latest 2.8.x running on EL7 using the `clapi` export / import functionality.  No alerts, no problems.  It has to be something in the configuration that isn't obvious.

**Comment by sandwedge** [comment]
A checkbox.  When you start dissecting the .cfg files line by line, you find it.

![dumba](https://cloud.githubusercontent.com/assets/11574720/25561492/93a1f054-2d33-11e7-9e78-bfee3aef00ba.png)

**Comment by btassite** [comment]
Good to know you solved your problem :) Just for the record, I have critical and other checkboxes checked, so my issue is not solved. (see #53)
