### ISSUE TITLE
nebmodule error

### ISSUE THREAD

**Issue by golgoth31** [centreon/centreon-engine#64]
Hi,
I have the following error in centengine.log:
Error: Module reloading failed: could not find symbol 'nebmodule_reload': /usr/lib64/centreon-engine/externalcmd.so: undefined symbol: nebmodule_reload

is-it normal ?

David

**Comment by ganoze** [comment]
Indeed this error should not be printed. I've added two commits to fix this.

51b763613caee7691a38fd675419939672c1e47b will reduce the message's severity to a Warning (not an Error) and a71ce9eedd182085c69a5541d5b3d756dacf2e2a will prevent the external command module to even print this Warning.

**Comment by joschi99** [comment]
I have the same issue on Centreon Engine 1.7.0

**Comment by ganoze** [comment]
For the 1.7 branch, this will be fixed in the 1.7.1 release.
