### ISSUE TITLE
Stalking-Output not in log/event

### ISSUE THREAD

**Issue by leo29041982** [centreon/centreon-engine#66]
Strangely the output does not appear in the logfile oder database.
I didn't find out why. Sounds like #59 

centengine 1.7.0

---

define host {
    host_name                      DEM_RZ_GLT_SW-RZ-GLT
    alias                          SW-RZ-GLT
    address                        172.29.23.250
    register                       1
    timezone                       :Europe/Berlin
    use                            generic-host
    _SNMPCOMMUNITY                 public
    _SNMPVERSION                   2c
    _HOST_ID                       83
}

---

define service {
    host_name                      DEM_RZ_GLT_SW-RZ-GLT
    service_description            Ping-LAN
    check_command                  check_icmp!3!200,20%!400,50%
    register                       1
    use                            Ping-LAN
    _SERVICE_ID                    24
}

define service {
    host_name                      DEM_RZ_GLT_SW-RZ-GLT
    service_description            NWC uptime
    check_command                  check_nwc_health!uptime!
    check_period                   24x7
    check_interval                 1
    retry_interval                 1
    register                       1
    use                            generic-service
    _SERVICE_ID                    26
}

define service {
    host_name                      DEM_RZ_GLT_SW-RZ-GLT
    service_description            NWC hardwarehealth
    check_command                  check_nwc_health!hardware-health!
    check_period                   24x7
    check_interval                 1
    retry_interval                 1
    register                       1
    use                            generic-service
    _SERVICE_ID                    28
}

define service {
    host_name                      DEM_RZ_GLT_SW-RZ-GLT
    service_description            NWC cpuload
    check_command                  check_nwc_health!cpu-load!-
    check_period                   24x7
    check_interval                 1
    retry_interval                 1
    register                       1
    use                            generic-service
    _SERVICE_ID                    27
}

---

define service {
    service_description            generic-service
    name                           generic-service
    contact_groups                 +Supervisors
    check_period                   24x7
    notification_period            24x7
    max_check_attempts             3
    check_interval                 5
    retry_interval                 1
    notification_interval          240
    notification_options           w,u,c,r,f,s
    stalking_options               o,w,u,c
    register                       0
    active_checks_enabled          1
    passive_checks_enabled         1
    notifications_enabled          1
}

define service {
    service_description            Ping-LAN
    name                           Ping-LAN
    check_command                  check_icmp!3!200,20%!400,50%
    check_period                   24x7
    notification_period            24x7
    max_check_attempts             3
    check_interval                 1
    retry_interval                 1
    notification_interval          240
    notification_options           w,u,c,r,f,s
    register                       0
    active_checks_enabled          1
    passive_checks_enabled         1
    notifications_enabled          1
    use                            generic-service
}

---

---
[1487077640] [22608] EXTERNAL COMMAND: SCHEDULE_FORCED_SVC_CHECK;DEM_RZ_GLT_SW-RZ-GLT;NWC cpuload;1487077639
[1487077640] [22608] EXTERNAL COMMAND: SCHEDULE_FORCED_SVC_CHECK;DEM_RZ_GLT_SW-RZ-GLT;NWC hardwarehealth;1487077639
[1487077640] [22608] EXTERNAL COMMAND: SCHEDULE_FORCED_SVC_CHECK;DEM_RZ_GLT_SW-RZ-GLT;NWC uptime;1487077639
[1487077640] [22608] EXTERNAL COMMAND: SCHEDULE_FORCED_SVC_CHECK;DEM_RZ_GLT_SW-RZ-GLT;Ping-LAN;1487077639
[1487077642] [22608] SERVICE ALERT: DEM_RZ_GLT_SW-RZ-GLT;NWC uptime;OK;HARD;1;OK - device is up since 347d 11h 26m 28s
[1487077642] [22608] SERVICE ALERT: DEM_RZ_GLT_SW-RZ-GLT;Ping-LAN;OK;HARD;1;OK - 172.29.23.250: rta 4,854ms, lost 0%

---
![image](https://cloud.githubusercontent.com/assets/24585227/22930170/46c77b36-f2bf-11e6-93dc-eb7e5350a3f2.png)

**Comment by ganoze** [comment]
Could you give more details on your issue ? In particular could you give a precise scenario with the current outcome and the expected one ?
