### ISSUE TITLE
Centreon-engine doesn't warn anymore on host unconsistent configuration

### ISSUE THREAD

**Issue by Sims24** [centreon/centreon-engine#78]
Hi, 

In release centreon-engine-1.7.1-2.el6.x86_64, I can create host without template in Centreon and without defined max_check_attempts without issue. 

Before (centreon-engine-daemon-1.5.2-1.el6.x86_64), the config pre flight check failed and I was not be able to deploy the configuration to my server.

centreon-engine-daemon-1.5.2-1.el6.x86_64 (Centreon 2.7.8)

```
Reading main configuration file '/usr/share/centreon/filesGeneration/nagiosCFG/2/nagiosCFG.DEBUG'.
Reading resource file '/usr/share/centreon//filesGeneration/nagiosCFG/2/resource.cfg'
Error Invalid max_check_attempts value for host 'Miaou-Fake'
Could not register host 'Host-Fake'
Cannot resolve non-existing host 'Miaou-Fake'
```

centreon-engine-1.7.1-2.el6.x86_64 (Centreon 2.8.5)

```
[1496829088] [27372] Reading resource file '/etc/centreon-engine/resource.cfg'
[1496829088] [27372] Warning: Host 'Miaou-Fake' has no services associated with it!
```

I'm not really sure that it's a centreon-engine issue, may be this is related to the way centreon generates the configuration. 

Thanks you for your lights,

**Comment by ganoze** [comment]
The behavior of some configuration parameters was reworked in Centreon Web 2.8 / Centreon Engine 1.7. The rationale behind these changes is that configuration parameters should have default values wherever possible. In the case of the _max_check_attempt_ parameter the default value is 3 if not defined anywhere (direct configuration of through inheritance).

**Comment by Sims24** [comment]
Ok, thanks. 

For other readers, result/symptom is a host pending forever in the monitoring.
