### ISSUE TITLE
Notifications problem

### ISSUE THREAD

**Issue by ganoze** [centreon/centreon-engine#8]
As reported by Martin Soltis:

I don't know how to set name of this topic.

Last night notifications from centreon engine going mad, and it sent many notifications in few seconds.
And of course i have escalations set to send notifications after 10 minutes.

And there is some interresting warning after, or before every notification

[1409706224] [15656] Warning: Check result queue contained results for service 'temp_core1' on host 'r2.example.com', but the service could not be found! Perhaps you forgot to define the ser
vice in your config files ?

I try to find some info, and found same warning, but it was related to nagios and two running instances. So i think, that here is different problem.

centreon engine is 1.4.6

**Comment by ganoze** [comment]
Does this issue still occurs with latest Centreon Engine (1.4.14) ?

**Comment by kom0do** [comment]
Hi,

no, it seems that this was one time problem, so i think you can close this issue. Thanks
