### ISSUE TITLE
Reload problem, for hostgroups

### ISSUE THREAD

**Issue by jben94** [centreon/centreon-engine#80]
Hi,

The change of hostgroup is not taken into account after a reload, it is necessary to make a restart.
The configuration files and centreon database are correct, but not centreon_storage database.

centreon web : 2.8.5
centreon cbd : 3.0.7
centreon engine : 1.7.2

Regards.

**Comment by ganoze** [comment]
Unfortunately I was not able to reproduce this issue. In my platform hosts are properly added and removed on reload. Could you give me a detailed scenario with group and member names (as this might influence objects containers) ?

**Comment by jben94** [comment]
Hi,

The problem does not arrive all the time.
For the moment, I have not managed to reproduce it.
I'll close the Issue. 

Sorry for the inconvenience !
