### ISSUE TITLE
livestatus.o loading disabled in Centreon 2.8

### ISSUE THREAD

**Issue by eLvErDe** [centreon/centreon-engine#97]
Hello,

```
Error: Could not load module '/usr/lib64/check_mk/livestatus.o': Module is using an old or unspecified version of the event broker API
```

I know Centreon official statement regarding mklive but may I highlight two things:
* livestatus provide a way to integrate with Nagvis which is a popular tool
* livestatus provide a way to integrate with thruk that provide a nagios like API to integrate with Android tools.

That's clearly a NEED for me and my customers and removing this support is a blocker.

Should I build my own centreon-engine with API check removed or is this incompatible for real ?

Regards, Adam.

**Comment by ganoze** [comment]
This is really incompatible.

Centreon Engine API and Nagios API (v3 and v4) have diverged a _lot_ and it is unlikely that any module will be able to work with these two engines.
